name: ledger_gui
description: A Ledger (CLI) GUI
publish_to: 'none'

version: 0.2.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: 5.2.5
  provider: ^6.0.5
  shimmer: ^3.0.0
  shared_preferences: ^2.2.1

  ledger_cli: ^0.2.2
  ledger_cli_flutter: ^0.2.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
